docker restart test added to nightly and strato_build_test pipelines

diff --git a/Jenkinsfile.nightly b/Jenkinsfile.nightly
--- a/Jenkinsfile.nightly
+++ b/Jenkinsfile.nightly
@@ -53,6 +53,21 @@ pipeline {
             sleep 1
           done
           echo "bloc is available through nginx - node is running"
+          echo "Restarting docker containers to simulate computer restart..."
+          docker-compose -p strato stop
+          docker-compose -p strato start
+          # Quick availability test again
+          until curl --silent --output /dev/null --fail --location ${NODE_HOST}/bloc/v2.2/users/
+          do
+            if [[ "$counter" -gt 120 ]]; then
+              echo "bloc took longer than 2 minutes to initialize! aborting."
+              exit 73
+            fi
+            echo "waiting for bloc to be available through nginx"
+            counter=$((counter+1))
+            sleep 1
+          done
+          echo "bloc is available through nginx - node is running"
         '''
       }
     }
