Fix Jenkinsfile

diff --git a/pipelines/Jenkinsfile.membership-deploy b/pipelines/Jenkinsfile.membership-deploy
--- a/pipelines/Jenkinsfile.membership-deploy
+++ b/pipelines/Jenkinsfile.membership-deploy
@@ -93,9 +93,70 @@ pipeline {
     stage('Deploy mercata-testnet2-membership') {
         // agent { label "mercata-testnet2-membership" } // is default
         steps {
-        script {
-            lib.deployStrato(NODE_DATA.NODE1)
-        }
+          sh '''#!/bin/bash -le
+            set -x
+            rm -rf strato-getting-started
+            git clone https://github.com/blockapps/strato-getting-started -b master
+            cp docker-compose.yml strato-getting-started/
+            cp docker-compose.vault.yml strato-getting-started/
+          '''
+
+          dir("strato-getting-started") {
+            // Copy .pem and .key for SSL
+            sh 'cp /datadrive/letsencrypt-ssl/server.pem ssl/certs/'
+            sh 'cp /datadrive/letsencrypt-ssl/server.key ssl/private/'
+            withCredentials([
+              usernamePassword(credentialsId: 'stripe-key', passwordVariable: 'STRIPE_SECRET_KEY', usernameVariable: 'STRIPE_PUBLISHABLE_KEY'),
+              usernamePassword(credentialsId: 'marketplace-testnet2-aws-iam-user', passwordVariable: 'AWS_IAM_USER_ACCESS_KEY', usernameVariable: 'AWS_IAM_USER_KEY_ID'),
+            ]) {
+              writeFile file: "run.sh", text: """#!/bin/bash
+                sudo \\
+                  NODE_HOST=membership.mercata-testnet2.blockapps.net \\
+                  HTTPS_PORT='443' \\
+                  OAUTH_DISCOVERY_URL=https://keycloak.blockapps.net/auth/realms/mercata-testnet2/.well-known/openid-configuration \\
+                  OAUTH_CLIENT_ID=mercata-testnet2-membership \\
+                  OAUTH_CLIENT_SECRET=89070133-62f6-4a06-a1ca-41b0594bb0a7 \\
+                  VAULT_URL=https://vault.blockapps.net:8093 \\
+                  certInfo='{"orgName":"BlockApps","orgUnit":"Mercata","commonName":"MembershipNode","access":true}' \\
+                  EXT_STORAGE_S3_ACCESS_KEY_ID='${AWS_IAM_USER_KEY_ID}' \\
+                  EXT_STORAGE_S3_SECRET_ACCESS_KEY='${AWS_IAM_USER_ACCESS_KEY}' \\
+                  EXT_STORAGE_S3_BUCKET='mercata-testnet2' \\
+                  STRIPE_PUBLISHABLE_KEY='${STRIPE_PUBLISHABLE_KEY}' \\
+                  STRIPE_SECRET_KEY='${STRIPE_SECRET_KEY}' \\
+                  MP_DAPP_ADDRESS='c93f9a422a4508a6501a63537291128122f7bcf2' \\
+                  CLIENT_URL=https://membership.mercata-testnet2.blockapps.net \\
+                  ./strato --single
+              """
+            }
+
+            sh 'chmod +x run.sh'
+
+            sh './run.sh'
+      
+            sh 'docker ps'
+
+            // Few quick tests
+            sh '''#!/bin/bash -le
+              check_availability() {
+                counter=0
+                until curl --silent --fail --location https://membership.mercata-testnet2.blockapps.net/health | jq .healthInfo.isHealthy | grep true
+                do
+                  if [[ "$counter" -gt 120 ]]; then
+                    echo "STRATO node took longer than 2 minutes to initialize! aborting."
+                    exit 73
+                  fi
+                  echo "waiting for STRATO health endpoint to be available through nginx"
+                  counter=$((counter+1))
+                  sleep 1
+                done
+                echo "STRATO health endpoint is available through nginx - node is running"
+              }
+              
+              check_availability
+            '''
+
+
+          }
         }
     }
   }
