added test sync stage

diff --git a/pipelines/Jenkinsfile.autobuild b/pipelines/Jenkinsfile.autobuild
--- a/pipelines/Jenkinsfile.autobuild
+++ b/pipelines/Jenkinsfile.autobuild
@@ -92,6 +92,7 @@ pipeline {
                 EXT_STORAGE_S3_BUCKET='tcommerce-dev' \\
                 MP_IS_BOOTNODE='true' \\
                 MP_DELAY_DEPLOYMENT='true' \\
+                network='mercata-hydrogen' \\
                 ./strato --single
             """
           }
@@ -121,6 +122,8 @@ pipeline {
 
             check_availability
           '''
+        // don't want it to get overwritten
+        sh "mv genesis-block.json genesis-block-official.json"
         }
         script {
           lib.generateGenesisBlock('.', 'strato-getting-started', null)
@@ -244,7 +247,7 @@ pipeline {
               set -x
               echo "Running apex unit tests"
               APEX_CONTAINER=$(docker ps --format '{{.Names}}' | grep 'apex.*1')
-# TEMPORARY DISABLING APEX TESTS UNTIL THEY ARE CLEANED UP AND FIXED
+              # TEMPORARY DISABLING APEX TESTS UNTIL THEY ARE CLEANED UP AND FIXED
               # docker exec -t -e NODE_ENV=test "$APEX_CONTAINER" ./run-tests.sh
             '''
           },
@@ -308,6 +311,63 @@ pipeline {
             }
           },
         )
+      }
+    }
+
+    stage('Test Sync'){
+      steps {
+        dir("strato-getting-started"){
+          sh './strato --wipe'
+          sh 'mv genesis-block-official.json genesis-block.json'
+          sh './run.sh'
+          sh '''#!/usr/bin/env bash
+            counter=0
+            until docker exec strato-apex-1 curl -s -f http://localhost:3009/health | jq .healthInfo.isHealthy | grep true
+            do
+                if (( $counter >= 120 )) ; then
+                    echo "Failure: STRATO did not rise and shine after two minutes. Something is wrong"
+                    exit 3
+                fi
+                sleep 1
+                counter=$((++counter))
+            done
+
+            WAIT_TIME=30
+
+            LAST_VM_BLOCK_NUM=0
+            LAST_SEQ_BLOCK_NUM=0
+            MAYBE_STALLED=false
+
+            IS_SYNCED=$(./strato --get-metadata | jq -r .isSynced)
+            while [ "$IS_SYNCED" != true ]; do
+                STATUS=$(docker exec strato-apex-1 curl -s -f http://localhost:3009/status )
+                if [ $? != 0 ]; then
+                    echo "Failure: unable to obtain status info from Apex; likely something has gone wrong"
+                    exit 2
+                fi
+                CUR_VM_BLOCK_NUM=$(jq -r .lastBlock.number <<< ${STATUS})
+                CUR_SEQ_BLOCK_NUM=$(jq -r .pbftData.sequence_number <<< ${STATUS})
+                echo "prev vm block #: ${LAST_VM_BLOCK_NUM}, cur vm block #: ${CUR_VM_BLOCK_NUM}"
+                echo "prev seq block #: ${LAST_SEQ_BLOCK_NUM}, cur seq block #: ${CUR_SEQ_BLOCK_NUM}"
+                if (( $CUR_VM_BLOCK_NUM == $LAST_VM_BLOCK_NUM ))  && \\
+                  (( $CUR_SEQ_BLOCK_NUM == $LAST_SEQ_BLOCK_NUM )) ; then
+                    # VM and Sequencer not gone forward. Perhaps stalled
+                    if [[ !$MAYBE_STALLED ]] ; then 
+                        MAYBE_STALLED=true
+                    else
+                        echo "Failure: node is likely stalled during sync; went ${WAIT_TIME} seconds without increasing block number"
+                        exit 1
+                    fi
+                fi
+                sleep $WAIT_TIME
+                IS_SYNCED=$(./strato --get-metadata | jq -r .isSynced)
+                LAST_VM_BLOCK_NUM=$CUR_VM_BLOCK_NUM
+                LAST_SEQ_BLOCK_NUM=$CUR_SEQ_BLOCK_NUM
+            done
+            echo "Sync successful!"
+            exit 0
+          '''
+        }
       }
     }
 
