Apply genesis-builder changes to Jenkinsfile.release

diff --git a/pipelines/Jenkinsfile.release b/pipelines/Jenkinsfile.release
--- a/pipelines/Jenkinsfile.release
+++ b/pipelines/Jenkinsfile.release
@@ -59,27 +59,107 @@ pipeline {
     stage('Deploy') {
 
       steps {
+        sh '''#!/bin/bash -le
+          set -x
+          rm -rf strato-getting-started
+          git clone https://github.com/blockapps/strato-getting-started -b STRATO-2852-shv-plus-genesis-builder
+          cp docker-compose.yml strato-getting-started/
+          cp docker-compose.vault.yml strato-getting-started/
+        '''
+
+        dir("strato-getting-started") {
+          // Copy .pem and .key for SSL
+          sh 'cp /home/ubuntu/letsencrypt-ssl/server.pem ssl/certs/'
+          sh 'cp /home/ubuntu/letsencrypt-ssl/server.key ssl/private/'
+
+          writeFile file: "run-vault.sh", text: """#!/bin/bash
+            sudo \\
+              ssl=true \\
+              HTTPS_PORT=8093 \\
+              INITIAL_OAUTH_DISCOVERY_URL='https://keycloak.blockapps.net/auth/realms/strato-devel/.well-known/openid-configuration' \\
+              INITIAL_OAUTH_ISSUER='https://keycloak.blockapps.net/auth/realms/strato-devel' \\
+              INITIAL_OAUTH_JWT_USERNAME_CLAIM='sub' \\
+              PASSWORD=123 \\
+              ./vault
+          """
+          sh 'chmod +x run-vault.sh'
+
+          sh './run-vault.sh'
+
+          // TODO: run node on https (also update check_availability function)
+          writeFile file: "run.sh", text: """#!/bin/bash
+            sudo \\
+              NODE_HOST=\$(</host) \\
+              BLOC_DEBUG=true \\
+              SLIPSTREAM_OPTIONAL=false \\
+              OAUTH_DISCOVERY_URL=https://keycloak.blockapps.net/auth/realms/strato-devel/.well-known/openid-configuration \\
+              OAUTH_CLIENT_ID=dev \\
+              OAUTH_CLIENT_SECRET=d5e67b8c-4fbf-42c6-a8d9-29a4dd13575f \\
+              VAULT_URL=https://\$(</host):8093 \\
+              VAULT_PROXY_DEBUG=true \\
+              requireCerts=false \\
+              certInfo='{"orgName":"BlockApps","orgUnit":"Engineering","commonName":"Test"}' \\
+              ./strato --single
+          """
+          sh 'chmod +x run.sh'
+
+          sh './run.sh'
+
+          sh 'docker ps'
+
+          // Few quick tests
           sh '''#!/bin/bash -le
-            set -x
-            rm -rf strato-getting-started
-            git clone https://github.com/blockapps/strato-getting-started
-            cp strato-worktree/docker-compose.yml strato-getting-started/
-            cd strato-getting-started
-            export NODE_HOST=$(</host)
-            export BLOC_DEBUG=true
-            export SLIPSTREAM_OPTIONAL=false
-            export OAUTH_DISCOVERY_URL=https://keycloak.blockapps.net/auth/realms/strato-devel/.well-known/openid-configuration
-            export OAUTH_CLIENT_ID=dev
-            export OAUTH_CLIENT_SECRET=d5e67b8c-4fbf-42c6-a8d9-29a4dd13575f
-            export PASSWORD=123
-            export requireCerts=false
-            export certInfo='{"orgName":"BlockApps","orgUnit":"Engineering","commonName":"Test"}'
-            ./strato --single
-            docker ps
-            # Few quick tests
             check_availability() {
               counter=0
-              until curl --silent --fail --location ${NODE_HOST}/health | jq .healthInfo.isHealthy | grep true
+              until curl --silent --fail --location $(</host)/health | jq .healthInfo.isHealthy | grep true
+              do
+                if [[ "$counter" -gt 120 ]]; then
+                  echo "STRATO node took longer than 2 minutes to initialize! aborting."
+                  exit 73
+                fi
+                echo "waiting for STRATO health endpoint to be available through nginx"
+                counter=$((counter+1))
+                sleep 1
+              done
+              echo "STRATO health endpoint is available through nginx - node is running"
+            }
+
+            check_availability
+          '''
+        }
+
+        dir("strato") {
+          // Build genesis-block.json
+          sh '''#!/bin/bash -le
+            myPub=$(docker exec strato_strato_1 bash -c "curl http://strato:8013/strato/v2.3/key" | python3 -c "import sys, json; print(json.load(sys.stdin)['pubkey'])")
+            sed "s/<PUBKEY>/$(echo $myPub)/g" x509-generator/subject.tpl.json > x509-generator/subject.json
+            stack run x509-generator -- \\
+              --issuer=x509-generator/rootCert.pem \\
+              --subject=x509-generator/subject.json \\
+              --key=x509-generator/rootPriv.pem
+            myCert=$(cat OutputCert.pem | perl -pe 's/\\n/\\\\n/g')
+            echo "[\\"$(echo $myCert)\\"]" > genesis-builder/certs.json
+            stack run genesis-builder -- \\
+              --input=genesis-builder/genesis-block.tpl.json \\
+              --faucets=genesis-builder/faucets.json \\
+              --validators=genesis-builder/validators.json \\
+              --admins=genesis-builder/admins.json \\
+              --certs=genesis-builder/certs.json \\
+              --output=../strato-getting-started/genesis-block.json'''
+        }
+
+        dir("strato-getting-started") {
+          sh './strato --wipe'
+
+          sh './run.sh'
+
+          sh 'docker ps'
+
+          // Few quick tests
+          sh '''#!/bin/bash -le
+            check_availability() {
+              counter=0
+              until curl --silent --fail --location $(</host)/health | jq .healthInfo.isHealthy | grep true
               do
                 if [[ "$counter" -gt 120 ]]; then
                   echo "STRATO node took longer than 2 minutes to initialize! aborting."
@@ -95,9 +175,10 @@ pipeline {
             echo "Restarting docker containers to simulate computer restart..."
             docker-compose -p strato --log-level ERROR stop
             docker-compose -p strato --log-level ERROR start
-            PASSWORD=${PASSWORD} ./strato --set-password
+
             check_availability
           '''
+        }
       }
     }
 
