release pipeline revamp

diff --git a/pipelines/obsolete/Jenkinsfile.release.pre2023 b/pipelines/obsolete/Jenkinsfile.release.pre2023
--- a/pipelines/obsolete/Jenkinsfile.release.pre2023
+++ b/pipelines/obsolete/Jenkinsfile.release.pre2023
@@ -4,8 +4,8 @@ pipeline {
   }
   options { disableConcurrentBuilds() }
   parameters {
-    string(name: 'GIT_TAG', defaultValue: 'tags/20231027-rc0', description: 'The strato-platform git tag to build as a release candidate. Use `tags/<tag_name>` format. NOTE: Other Refspec types are not supported.')
-    string(name: 'RELEASE_VERSION', defaultValue: '20231027', description: 'The version tag for the future release')
+    string(name: 'GIT_TAG', defaultValue: 'tags/0.0.0-rc0', description: 'The strato-platform git tag to build as a release candidate. Use `tags/<tag_name>` format. NOTE: Other Refspec types are not supported.')
+    string(name: 'RELEASE_VERSION', defaultValue: '0.0.0', description: 'The version tag for the future release')
   }
   stages {
     stage('Prepare') {
@@ -73,7 +73,7 @@ pipeline {
           // Copy .pem and .key for SSL
           sh 'cp /home/ubuntu/letsencrypt-ssl/server.pem ssl/certs/'
           sh 'cp /home/ubuntu/letsencrypt-ssl/server.key ssl/private/'
-
+      
           writeFile file: "run-vault.sh", text: """#!/bin/bash
             sudo \\
               ssl=true \\
@@ -85,45 +85,31 @@ pipeline {
               ./vault
           """
           sh 'chmod +x run-vault.sh'
-
+      
           sh './run-vault.sh'
-
+  
           // TODO: run node on https (also update check_availability function)
-          withCredentials([
-              usernamePassword(credentialsId: 'stripe-key', passwordVariable: 'STRIPE_SECRET_KEY', usernameVariable: 'STRIPE_PUBLISHABLE_KEY'),
-              usernamePassword(credentialsId: 'marketplace-global-admin', passwordVariable: 'GLOBAL_ADMIN_PASSWORD', usernameVariable: 'GLOBAL_ADMIN_NAME'),
-              usernamePassword(credentialsId: 'marketplace-dev-aws-iam-user', passwordVariable: 'AWS_IAM_USER_ACCESS_KEY', usernameVariable: 'AWS_IAM_USER_KEY_ID'),
-          ]) {
-            writeFile file: "run.sh", text: """#!/bin/bash
-              sudo \\
-                NODE_HOST=\$(</host) \\
-                SLIPSTREAM_OPTIONAL=false \\
-                OAUTH_DISCOVERY_URL=https://keycloak.blockapps.net/auth/realms/strato-devel/.well-known/openid-configuration \\
-                OAUTH_CLIENT_ID=dev \\
-                OAUTH_CLIENT_SECRET=d5e67b8c-4fbf-42c6-a8d9-29a4dd13575f \\
-                VAULT_URL=https://\$(</host):8093 \\
-                VAULT_PROXY_DEBUG=true \\
-                certInfo='{"orgName":"BlockApps","orgUnit":"Engineering","commonName":"Test"}' \\
-                STRIPE_PUBLISHABLE_KEY='${STRIPE_PUBLISHABLE_KEY}' \\
-                STRIPE_SECRET_KEY='${STRIPE_SECRET_KEY}' \\
-                GLOBAL_ADMIN_NAME='${GLOBAL_ADMIN_NAME}' \\
-                GLOBAL_ADMIN_PASSWORD='${GLOBAL_ADMIN_PASSWORD}' \\
-                EXT_STORAGE_S3_ACCESS_KEY_ID='${AWS_IAM_USER_KEY_ID}' \\
-                EXT_STORAGE_S3_SECRET_ACCESS_KEY='${AWS_IAM_USER_ACCESS_KEY}' \\
-                EXT_STORAGE_S3_BUCKET='tcommerce-dev' \\
-                MP_IS_BOOTNODE='true' \\
-                MP_DELAY_DEPLOYMENT='true' \\
-                ./strato --single
-            """
-          }
+          writeFile file: "run.sh", text: """#!/bin/bash
+            sudo \\
+              NODE_HOST=\$(</host) \\
+              BLOC_DEBUG=true \\
+              SLIPSTREAM_OPTIONAL=false \\
+              OAUTH_DISCOVERY_URL=https://keycloak.blockapps.net/auth/realms/strato-devel/.well-known/openid-configuration \\
+              OAUTH_CLIENT_ID=dev \\
+              OAUTH_CLIENT_SECRET=d5e67b8c-4fbf-42c6-a8d9-29a4dd13575f \\
+              VAULT_URL=https://\$(</host):8093 \\
+              VAULT_PROXY_DEBUG=true \\
+              certInfo='{"orgName":"BlockApps","orgUnit":"Engineering","commonName":"Test"}' \\
+              ./strato --single
+          """
           sh 'chmod +x run.sh'
-
+      
           sh './run.sh'
-
+      
           sh 'docker ps'
-
+      
           // Few quick tests
-          writeFile file: "check_availability.sh", text: '''#!/bin/bash -le
+          sh '''#!/bin/bash -le
             check_availability() {
               counter=0
               until curl --silent --fail --location $(</host)/health | jq .healthInfo.isHealthy | grep true
@@ -141,14 +127,11 @@ pipeline {
 
             check_availability
           '''
-          sh 'chmod +x check_availability.sh'
-          sh './check_availability.sh'
-          // don't want it to get overwritten
-          sh "cp genesis-block.json genesis-block-official.json"
         }
-
+  
         script {
           lib.generateGenesisBlock('strato-worktree', 'strato-getting-started', null)
+
         }
 
         dir("strato-getting-started") {
@@ -159,13 +142,30 @@ pipeline {
           sh 'docker ps'
 
           // Few quick tests
-          sh './check_availability.sh'
+          sh '''#!/bin/bash -le
+            check_availability() {
+              counter=0
+              until curl --silent --fail --location $(</host)/health | jq .healthInfo.isHealthy | grep true
+              do
+                if [[ "$counter" -gt 120 ]]; then
+                  echo "STRATO node took longer than 2 minutes to initialize! aborting."
+                  exit 73
+                fi
+                echo "waiting for STRATO health endpoint to be available through nginx"
+                counter=$((counter+1))
+                sleep 1
+              done
+              echo "STRATO health endpoint is available through nginx - node is running"
+            }
 
-          echo "Restarting docker containers to simulate computer reboot..."
-          sh 'docker compose -p strato stop'
-          sh 'docker compose -p strato start'
+            check_availability
 
-          sh './check_availability.sh'
+            echo "Restarting docker containers to simulate computer restart..."
+            docker compose -p strato stop
+            docker compose -p strato start
+
+            check_availability
+          '''
         }
 
         script {
@@ -195,13 +195,55 @@ pipeline {
       }
     }
 
-//    stage('Some quick tests') {
-//      steps {
-//        parallel(
-//
-//        )
-//      }
-//    }
+    stage('Some quick tests') {
+      steps {
+        parallel(
+          'Apex tests': {
+            sh '''#!/bin/bash -le
+              set -x
+              echo "Running apex unit tests"
+              APEX_CONTAINER=$(docker ps --format '{{.Names}}' | grep 'apex.*1')
+# TEMPORARY DISABLING APEX TESTS UNTIL THEY ARE CLEANED UP AND FIXED
+              # docker exec -t -e NODE_ENV=test "$APEX_CONTAINER" ./run-tests.sh
+            '''
+          },
+
+          'STRATO API Tests': {
+            withCredentials([
+              usernamePassword(credentialsId: 'blockapps-cd-github', passwordVariable: 'GITHUB_TOKEN', usernameVariable: 'GITHUB_USERNAME')
+            ]) {
+
+              sh '''#!/bin/bash -le
+                set -x
+                # Re-cloning the repo might be redundant but we'll follow same approach as other tests. And the docker rebuild should be quick with docker layer caches.
+                rm -rf strato-api-tests
+                git clone -b develop https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/blockapps/strato-api-tests.git
+                cd strato-api-tests
+                #git checkout develop # we must not checkout the custom branch here - we must test with develop branch of strato-api-tests here as well as in the nightly job.
+                docker build --tag strato-api-tests .
+                docker run \
+                  -e OAUTH_DISCOVERY_URL=https://keycloak.blockapps.net/auth/realms/strato-devel/.well-known/openid-configuration \
+                  -e OAUTH_CLIENT_ID=dev \
+                  -e OAUTH_CLIENT_SECRET=d5e67b8c-4fbf-42c6-a8d9-29a4dd13575f \
+                  -e STRATO_NODE_URL=http://172.17.0.1:80 \
+                  -e DEBUG_LOG=false \
+                  strato-api-tests
+              '''
+            }
+          },
+
+          'BA-Rest Tests': {
+            sh '''#!/bin/bash -le
+              set -x
+              echo "Running ba-rest E2E tests"
+              cd strato-worktree/blockapps-rest
+              DOCKER_HOST=172.17.0.1 # on "Docker for Mac" use "docker.for.mac.localhost" special reserved ip instead
+              docker build -f Dockerfile.test --build-arg host=${DOCKER_HOST} --no-cache .
+            '''
+          },
+        )
+      }
+    }
 
     stage('Release') {
       steps {
@@ -234,10 +276,8 @@ pipeline {
               sleep 5
               github-release upload $STRATOGS_RELEASE_DETAILS_STABLE --name "docker-compose.yml" --file ./docker-compose.yml
               github-release upload $STRATOGS_RELEASE_DETAILS_STABLE --name "docker-compose.vault.yml" --file ./docker-compose.vault.yml
-              github-release upload $STRATOGS_RELEASE_DETAILS_STABLE --name "docker-compose.identity.yml" --file ./docker-compose.identity.yml
               github-release upload $STRATOGS_RELEASE_DETAILS_STABLE --name "docker-compose.ecr.yml" --file ./docker-compose.ecr.yml
               github-release upload $STRATOGS_RELEASE_DETAILS_STABLE --name "docker-compose.vault.ecr.yml" --file ./docker-compose.vault.ecr.yml
-              github-release upload $STRATOGS_RELEASE_DETAILS_STABLE --name "docker-compose.identity.ecr.yml" --file ./docker-compose.identity.ecr.yml
             '''
 
             // Merge release code to master
