test github action workflow

diff --git a/.github/workflows/main-and-staging-protection.yaml b/.github/workflows/main-and-staging-protection.yaml
--- a/.github/workflows/main-and-staging-protection.yaml
+++ b/.github/workflows/main-and-staging-protection.yaml
@@ -7,8 +7,18 @@ jobs:
   check_branch:
     runs-on: ubuntu-latest
     steps:
+      - name: Check branch 1
+        if: github.base_ref == 'master' && github.head_ref != 'staging'
+        run: |
+          echo "ERROR: You can only merge to 'master' from 'staging'."
+          exit 1
+      - name: Check branch 2
+        if: github.base_ref == 'staging' && github.head_ref != 'develop'
+        run: |
+          echo "ERROR: You can only merge to 'staging' from 'devel'."
+          exit 1
       - name: Check branch 3
-        if: github.base_ref == 'devel' && github.head_ref != 'my-non-existent-branch'
+        if: github.base_ref == 'develop' && github.head_ref != 'my-non-existent-branch'
         run: |
           echo "ERROR: You can only merge to 'devel' from 'my-non-existent-branch' (TESTING). Trigger GitHub Action \#1"
           exit 1
